# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
#    branches: [ "main" ]
    tags: ['v*']
#  pull_request:
#    branches: [ "main" ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: registry.digitalocean.com
  # github.repository as <account>/<repo>
  IMAGE_NAME: keibi/temp

jobs:

  build:
    runs-on: ubuntu-latest
    environment: golang
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.19

    - name: Build
      env: # Or as an environment variable
        CI_ACCESS_TOKEN: ${{ secrets.CI_ACCESS_TOKEN }}
        GITHUBCI_TOKEN: ${{ secrets.GITHUBCI_TOKEN }}
      run: |
        echo -e "machine gitlab.com login gitlab-ci-token password ${{ secrets.CI_ACCESS_TOKEN }}" > ~/.netrc
        echo -e "machine github.com login api password ${{ secrets.GITHUBCI_TOKEN }}" >> ~/.netrc
        make build         

#    - name: Set up Docker Buildx
#      uses: docker/setup-buildx-action@v2
#
#    # https://github.com/docker/login-action
#    - name: Log into registry ${{ env.REGISTRY }}
#      if: github.event_name != 'pull_request'
#      uses: docker/login-action@v2
#      with:
#        registry: ${{ env.REGISTRY }}
#        username: ${{ secrets.DO_API_TOKEN }}
#        password: ${{ secrets.DO_API_TOKEN }}
#
#    # Extract metadata (tags, labels) for Docker
#    # https://github.com/docker/metadata-action
#    - name: Extract Docker metadata
#      id: meta
#      uses: docker/metadata-action@v4
#      with:
#        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
#        tags: |
#          type=schedule
#          type=ref,event=branch
#          type=ref,event=pr
#          type=semver,pattern={{version}}
#
#    # Build and push Docker image with Buildx (don't push on PR)
#    # https://github.com/docker/build-push-action
#    - name: Build and push Docker image
#      id: build-and-push
#      uses: docker/build-push-action@v4
#      with:
#        context: .
#        push: ${{ github.event_name != 'pull_request' }}
#        tags: ${{ steps.meta.outputs.tags }}
#        labels: ${{ steps.meta.outputs.labels }}
#        cache-from: type=gha
#        cache-to: type=gha,mode=max
